language: objective-c

branches:
 only:
 - master

xcode_workspace: DateTools.xcworkspace
xcode_scheme: DateToolsTests
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2


before_install:
- gem install cocoapods
- pod install

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail && xcodebuild -workspace DateTools.xcworkspace -scheme DateToolsTests -sdk iphonesimulator test | xcpretty -c
